[build]
	publish = "docs"

[[headers]]
	for = "/assets/*"
	[headers.values]
		cache-control = '''
		max-age=31536000,
		immutable
		'''

[[redirects]]
	from = "/fr/*"
	to = "/fr/404.html"
	status = 404
