name: Take screenshots

on:
  workflow_dispatch:

concurrency:
  group: take-screenshots
  cancel-in-progress: true

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Retrieve Node version
        run: echo "nvmrc=$(cat .nvmrc)" >> $GITHUB_ENV
        id: nvmrc

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.nvmrc }}"
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          cd argos
          npm ci
          npm run playwright install --with-deps chromium

      - name: Build the website
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          PLAUSIBLE_SCRIPT_SRC: ${{ secrets.PLAUSIBLE_SCRIPT_SRC }}
        run: npm run build

      - name: Take screenshots with Playwright
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          PLAUSIBLE_SCRIPT_SRC: ${{ secrets.PLAUSIBLE_SCRIPT_SRC }}
        run: |
          cd argos
          npm run playwright test

      - name: Upload screenshots to Argos
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
        run: |
          cd argos
          npm run argos upload ./screenshots
